# ==========================================
# 科技树配置 - 辐射状科技树
# ==========================================

TECH_TREE_VERSION = 2

TECH_TREE = {
    # ==================== 中心节点 ====================
    'gene_engineering': {
        'name': '基因工程',
        'description': '基础基因操作技术，科技树的起点',
        'level': 1,
        'max_level': 5,
        'unlocked': True,
        'unlock_requirement': None,
        'branch': 'root',
        'tree_angle': None,
        'tree_radius': 0,
        'effects': {
            1: '解锁基础基因操作功能',
            2: '解锁育种和编辑分支',
            3: '解锁变异和强化分支',
            4: '解锁高级编辑技术',
            5: '解锁终极基因组强化',
        },
        'costs': {
            2: {'battle_materials': 30},
            3: {'battle_materials': 60},
            4: {'battle_materials': 150, 'gacha_currency': 10},
            5: {'battle_materials': 300, 'gacha_currency': 20},
        },
    },

    # ==================== 育种分支 (右侧, 0°) ====================
    'embryo_engineering': {
        'name': '胚胎工程',
        'description': '加速繁殖过程的技术',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 2),
        'branch': 'breeding',
        'tree_angle': 0,
        'tree_radius': 1,
        'effects': {
            1: '繁殖速度 +50%',
            2: '繁殖速度 +100%',
            3: '繁殖速度 +150%',
        },
        'costs': {
            1: {'battle_materials': 50},
            2: {'battle_materials': 150},
            3: {'battle_materials': 300, 'gacha_currency': 20},
        },
    },
    'clone_tech': {
        'name': '克隆技术',
        'description': '复制已有基因组合',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('embryo_engineering', 2),
        'branch': 'breeding',
        'tree_angle': -18,
        'tree_radius': 2,
        'effects': {
            1: '解锁克隆功能',
            2: '克隆成功率提升',
        },
        'costs': {
            1: {'battle_materials': 100, 'gacha_currency': 10},
            2: {'battle_materials': 250, 'gacha_currency': 25},
        },
    },
    'fast_breeding': {
        'name': '快速繁殖',
        'description': '进一步缩短繁殖周期',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('embryo_engineering', 2),
        'branch': 'breeding',
        'tree_angle': 18,
        'tree_radius': 2,
        'effects': {
            1: '繁殖速度额外 +30%',
            2: '繁殖速度额外 +60%',
        },
        'costs': {
            1: {'battle_materials': 80},
            2: {'battle_materials': 200},
        },
    },
    'auto_breeding': {
        'name': '自动繁殖',
        'description': '自动随机选择雌雄卡牌进行不间断繁殖',
        'level': 0,
        'max_level': 1,
        'unlocked': False,
        'unlock_requirement': ('fast_breeding', 2),
        'branch': 'breeding',
        'tree_angle': 18,
        'tree_radius': 3,
        'effects': {
            1: '解锁自动繁殖功能，自动随机配对繁殖',
        },
        'costs': {
            1: {'battle_materials': 400, 'gacha_currency': 50},
        },
    },
    'gene_optimize': {
        'name': '基因优化',
        'description': '优化新生个体的基础基因质量',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('embryo_engineering', 3),
        'branch': 'breeding',
        'tree_angle': 0,
        'tree_radius': 3,
        'effects': {
            1: '新生个体基础属性 +3',
            2: '新生个体基础属性 +6',
        },
        'costs': {
            1: {'battle_materials': 200, 'gacha_currency': 20},
            2: {'battle_materials': 500, 'gacha_currency': 50},
        },
    },
    'ivf_tech': {
        'name': '体外受精',
        'description': '手动提取配子并在体外结合成新胚胎',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('embryo_engineering', 3),
        'branch': 'breeding',
        'tree_angle': -18,
        'tree_radius': 3,
        'effects': {
            1: '解锁配子提取与体外受精功能',
            2: '可提取特定基因的配子',
        },
        'costs': {
            1: {'battle_materials': 150, 'gacha_currency': 15},
            2: {'battle_materials': 400, 'gacha_currency': 40},
        },
    },

    # ==================== 变异分支 (上方, 90°) ====================
    'mutation_study': {
        'name': '变异学',
        'description': '研究辐射变异的技术',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 3),
        'branch': 'mutation',
        'tree_angle': 90,
        'tree_radius': 1,
        'effects': {
            1: '解锁射线变异操作',
            2: '变异正向概率提升',
            3: '解锁重度变异',
        },
        'costs': {
            1: {'battle_materials': 50},
            2: {'battle_materials': 120},
            3: {'battle_materials': 250},
        },
    },
    'evolution_boost': {
        'name': '进化促进',
        'description': '加速基因变异和进化',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('mutation_study', 2),
        'branch': 'mutation',
        'tree_angle': 68,
        'tree_radius': 2,
        'effects': {
            1: '变异概率 +5%',
            2: '变异概率 +10%',
            3: '变异概率 +15%',
        },
        'costs': {
            1: {'battle_materials': 100},
            2: {'battle_materials': 200},
            3: {'battle_materials': 400, 'gacha_currency': 30},
        },
    },
    'directed_mutation': {
        'name': '定向变异',
        'description': '定向引导基因变异方向',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('mutation_study', 2),
        'branch': 'mutation',
        'tree_angle': 112,
        'tree_radius': 2,
        'effects': {
            1: '解锁定向变异操作',
            2: '定向变异效率提升',
        },
        'costs': {
            1: {'battle_materials': 150, 'gacha_currency': 15},
            2: {'battle_materials': 350, 'gacha_currency': 30},
        },
    },
    'radiation_resist': {
        'name': '抗辐射',
        'description': '减少辐射变异的负面影响',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('mutation_study', 3),
        'branch': 'mutation',
        'tree_angle': 90,
        'tree_radius': 3,
        'effects': {
            1: '变异负面概率 -15%',
            2: '变异负面概率 -30%',
        },
        'costs': {
            1: {'battle_materials': 200},
            2: {'battle_materials': 400, 'gacha_currency': 20},
        },
    },
    'gene_isolation': {
        'name': '基因隔离',
        'description': '保护特定基因免受变异影响',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('radiation_resist', 2),
        'branch': 'mutation',
        'tree_angle': 68,
        'tree_radius': 4,
        'effects': {
            1: '解锁基因隔离保护',
            2: '可保护多个基因',
        },
        'costs': {
            1: {'battle_materials': 500, 'gacha_currency': 30},
            2: {'battle_materials': 1000, 'gacha_currency': 60},
        },
    },

    # ==================== 基因编辑分支 (左侧, 180°) ====================
    'methylation_tech': {
        'name': '甲基化技术',
        'description': '基因甲基化操作技术',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 2),
        'branch': 'editing',
        'tree_angle': 160,
        'tree_radius': 1,
        'effects': {
            1: '解锁甲基化操作',
            2: '解锁去甲基化操作',
        },
        'costs': {
            1: {'battle_materials': 60},
            2: {'battle_materials': 150},
        },
    },
    'gene_mapping': {
        'name': '基因定位',
        'description': '将连续基因组序列划分为独立基因区域，揭示每个基因的精确位置',
        'level': 0,
        'max_level': 1,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 2),
        'branch': 'editing',
        'tree_angle': 200,
        'tree_radius': 1,
        'effects': {
            1: '在基因序列显示中标示基因坐标边界',
        },
        'costs': {
            1: {'battle_materials': 40},
        },
    },
    'gene_splicing': {
        'name': '基因拼接',
        'description': '将不同基因片段连接',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 4),
        'branch': 'editing',
        'tree_angle': 180,
        'tree_radius': 1,
        'effects': {
            1: '解锁基因拼接功能',
            2: '拼接成功率提升',
            3: '解锁基因片段库',
        },
        'costs': {
            1: {'battle_materials': 100},
            2: {'battle_materials': 250},
            3: {'battle_materials': 500, 'gacha_currency': 30},
        },
    },
    'gene_library': {
        'name': '基因库',
        'description': '存储和检索基因片段',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('gene_splicing', 2),
        'branch': 'editing',
        'tree_angle': 180,
        'tree_radius': 2,
        'effects': {
            1: '解锁基因库功能',
            2: '基因库容量提升',
            3: '解锁基因交易',
        },
        'costs': {
            1: {'battle_materials': 200, 'gacha_currency': 20},
            2: {'battle_materials': 400, 'gacha_currency': 40},
            3: {'battle_materials': 800, 'gacha_currency': 60},
        },
    },
    'crispr_tech': {
        'name': 'CRISPR编辑',
        'description': '精确编辑基因序列',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 4),
        'branch': 'editing',
        'tree_angle': 140,
        'tree_radius': 1,
        'effects': {
            1: '解锁精确基因编辑',
            2: '编辑精度提升',
            3: '解锁基因敲除',
        },
        'costs': {
            1: {'battle_materials': 150},
            2: {'battle_materials': 350, 'gacha_currency': 20},
            3: {'battle_materials': 700, 'gacha_currency': 50},
        },
    },
    'gene_activate': {
        'name': '基因激活',
        'description': '唤醒被甲基化沉默的基因',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('crispr_tech', 2),
        'branch': 'editing',
        'tree_angle': 125,
        'tree_radius': 2,
        'effects': {
            1: '可激活甲基化技能基因',
            2: '激活成功率提升',
        },
        'costs': {
            1: {'battle_materials': 300, 'gacha_currency': 20},
            2: {'battle_materials': 600, 'gacha_currency': 40},
        },
    },
    'chromo_duplicate': {
        'name': '染色体复制',
        'description': '复制整条染色体到目标卡牌',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('gene_splicing', 3),
        'branch': 'editing',
        'tree_angle': 200,
        'tree_radius': 2,
        'effects': {
            1: '解锁染色体复制功能',
            2: '复制精度提升',
        },
        'costs': {
            1: {'battle_materials': 400, 'gacha_currency': 30},
            2: {'battle_materials': 800, 'gacha_currency': 50},
        },
    },

    # ==================== 强化分支 (下方, 270°) ====================
    'skill_enhance': {
        'name': '技能强化',
        'description': '强化战斗技能效果',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 3),
        'branch': 'enhance',
        'tree_angle': 295,
        'tree_radius': 1,
        'effects': {
            1: '技能效果 +10%',
            2: '技能效果 +20%',
            3: '技能效果 +30%',
        },
        'costs': {
            1: {'battle_materials': 80},
            2: {'battle_materials': 200},
            3: {'battle_materials': 400, 'gacha_currency': 20},
        },
    },
    'hybrid_enhance': {
        'name': '杂种优势利用',
        'description': '优化杂交组合，增强杂种优势效果',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 3),
        'branch': 'enhance',
        'tree_angle': 270,
        'tree_radius': 1,
        'effects': {
            1: '解锁杂种优势显示',
            2: '杂种优势 +50%',
        },
        'costs': {
            1: {'battle_materials': 100},
            2: {'battle_materials': 300},
        },
    },
    'super_hybrid': {
        'name': '超级杂交',
        'description': '杂种优势扩展至全部属性',
        'level': 0,
        'max_level': 1,
        'unlocked': False,
        'unlock_requirement': ('hybrid_enhance', 2),
        'branch': 'enhance',
        'tree_angle': 270,
        'tree_radius': 2,
        'effects': {
            1: '杂种优势加成扩展至所有属性',
        },
        'costs': {
            1: {'battle_materials': 500, 'gacha_currency': 50},
        },
    },
    'life_extension': {
        'name': '寿命延长',
        'description': '延长卡牌的生命周期',
        'level': 0,
        'max_level': 2,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 4),
        'branch': 'enhance',
        'tree_angle': 245,
        'tree_radius': 1,
        'effects': {
            1: '寿命属性 +20%',
            2: '寿命属性 +40%',
        },
        'costs': {
            1: {'battle_materials': 200},
            2: {'battle_materials': 500},
        },
    },
    'genome_boost': {
        'name': '基因组强化',
        'description': '增强基因组增强系统的效果',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 5),
        'branch': 'enhance',
        'tree_angle': 320,
        'tree_radius': 1,
        'effects': {
            1: '基因组增强效果 +20%',
            2: '基因组增强效果 +40%',
            3: '基因组增强效果 +60%',
        },
        'costs': {
            1: {'battle_materials': 300},
            2: {'battle_materials': 600, 'gacha_currency': 30},
            3: {'battle_materials': 1200, 'gacha_currency': 60},
        },
    },
    'stat_break': {
        'name': '属性突破',
        'description': '突破属性上限限制',
        'level': 0,
        'max_level': 3,
        'unlocked': False,
        'unlock_requirement': ('genome_boost', 2),
        'branch': 'enhance',
        'tree_angle': 320,
        'tree_radius': 2,
        'effects': {
            1: '属性上限 +10%',
            2: '属性上限 +20%',
            3: '属性上限 +30%',
        },
        'costs': {
            1: {'battle_materials': 500},
            2: {'battle_materials': 1000, 'gacha_currency': 50},
            3: {'battle_materials': 2000, 'gacha_currency': 100},
        },
    },

    # ==================== 后勤分支 (左下, 210-240°) ====================
    'card_storage': {
        'name': '卡牌库房',
        'description': '拓展卡牌库的存储上限，每级消耗大量战斗材料',
        'level': 0,
        'max_level': 999,
        'unlocked': False,
        'unlock_requirement': ('gene_engineering', 2),
        'branch': 'logistics',
        'tree_angle': 225,
        'tree_radius': 1,
        'effects': {},
    },
    'spirit_small': {
        'name': '小精灵',
        'description': '战斗胜利后获得1张随机低质量卡牌',
        'level': 0,
        'max_level': 1,
        'unlocked': False,
        'unlock_requirement': ('card_storage', 3),
        'branch': 'logistics',
        'tree_angle': 240,
        'tree_radius': 2,
        'effects': {
            1: '战后获得1张随机低质量卡牌',
        },
        'costs': {
            1: {'battle_materials': 300},
        },
    },
    'spirit_medium': {
        'name': '中精灵',
        'description': '战斗胜利后获得2张随机低质量卡牌（替换小精灵）',
        'level': 0,
        'max_level': 1,
        'unlocked': False,
        'unlock_requirement': ('spirit_small', 1),
        'branch': 'logistics',
        'tree_angle': 225,
        'tree_radius': 3,
        'effects': {
            1: '战后获得2张随机低质量卡牌（替换小精灵）',
        },
        'costs': {
            1: {'battle_materials': 800},
        },
    },
    'spirit_large': {
        'name': '大精灵',
        'description': '战斗胜利后获得1雄1雌随机低质量卡牌（替换中精灵）',
        'level': 0,
        'max_level': 1,
        'unlocked': False,
        'unlock_requirement': ('spirit_medium', 1),
        'branch': 'logistics',
        'tree_angle': 210,
        'tree_radius': 4,
        'effects': {
            1: '战后获得1雄1雌随机低质量卡牌（替换中精灵）',
        },
        'costs': {
            1: {'battle_materials': 2000, 'gacha_currency': 100},
        },
    },
}

# 科技分支视觉配置
TREE_BRANCHES = {
    'root': {
        'name': '核心',
        'color': '#ffd700',
        'bg': '#2a1f00',
    },
    'breeding': {
        'name': '育种',
        'color': '#4a9eff',
        'bg': '#0a1a3a',
    },
    'mutation': {
        'name': '变异',
        'color': '#4ade80',
        'bg': '#0a2a1a',
    },
    'editing': {
        'name': '基因编辑',
        'color': '#c084fc',
        'bg': '#1a0a2a',
    },
    'enhance': {
        'name': '强化',
        'color': '#fb923c',
        'bg': '#2a1a0a',
    },
    'logistics': {
        'name': '后勤',
        'color': '#50c878',
        'bg': '#0a2a1a',
    },
}

# ==================== 繁殖速度配置 ====================
BREEDING_CONFIG = {
    'base_duration': 30,
    'min_duration': 5,
    'speed_per_level': 0.5,
}

# ==================== 初始卡牌配置 ====================
INITIAL_CARDS_CONFIG = {
    'cards': [
        {'name': '铁壁卫士', 'gender': 'male'},
        {'name': '疾风剑士', 'gender': 'male'},
        {'name': '治愈之泉', 'gender': 'female'},
        {'name': '暗影猎手', 'gender': 'female'},
        {'name': '磐石守护', 'gender': 'male'},
        {'name': '星辉使者', 'gender': 'female'},
    ],
}
